// Created by Crowbar 0.74

// Stored modelname (without quotes): "D:\Compiling\Projects\Wan_Deagle_Stryker\Silver\w_deagle.mdl"
$modelname "w_deagle.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "world_deagle"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "Line01" -6.05 -5.37 -0.11 10.7 6.4 1.99

$sequence "idle" {
	"w_deagle_anims\idle"
	fps 30
}
