// Created by Crowbar 0.74

// Stored modelname (without quotes): "C:\Documents and Settings\Administrator\Desktop\Sako_M95_ak47\w_"
$modelname "w_galil.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "w_galil"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "p_galil" -16.82 -11.54 0 32.029999 6.61 5.94

$sequence "idle" {
	"w_galil_anims\idle"
	fps 30
}
