// Created by Crowbar 0.74

// Stored modelname (without quotes): "C:\WINDOWS\Desktop\HLMV\GlockCustom\W\glock\w_glock18.mdl"
$modelname "w_glock18.mdl"
$cd "."
$cdtexture "."
$cliptotextures
$scale 1.0

$bodygroup "studio"
{
	studio "world_glock18"
}

$flags 0


$cbox 0 0 0 0 0 0

$bbox 0 0 0 0 0 0

$hbox 0 "skin01" -0.65 -6.07 -2.79 0.62 5.07 4.16

$sequence "idle" {
	"w_glock18_anims\idle"
	fps 30
}
